### PR TITLE
Labeling the Docker image

### PR DESCRIPTION
**Pull request by dminca**
Add `--build-arg` during `docker build`:
* `BUILD_DATE`
* `VERSION`
* `VCS_URL`
* `VCS_REF`

If I'm missing some labels, feel free to fill the spot :sunglasses:

### CODE REVIEW

**Comment by pahakalle** [comment]
Is this going the get merged at some point?

**Comment by dminca** [comment]
Almost a year passed, I think the project has been abandoned :disappointed:

**Comment by pahakalle** [comment]
well shit...
hqdefault

**Comment by steev** [comment]
Can you check that I got the correct commits in? I did it manually locally because I was doing something else at the time so let me know if there's anything missed please!

**Comment by dminca** [comment]
@steev looks good. Also apply patch 571af88f5 , I forgot to remove the name from that one.

Thanks

**Comment by dminca** [comment]
Merged in #13 and synced with master branch

**Comment by steev** [comment]
Should be done as well

**Pull request closed without merging**
