### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by NonCreature0714**
Line 2: Updated depreciated "maintainer" to "label"
Line 5&6: Indented multi-line run command for readability, and changed "&&" to the beginning of the second line so it is more clear that this is a multi-line RUN

### CODE REVIEW

**Comment by pahakalle** [comment]
Is this different from #15

**Comment by NonCreature0714** [comment]
@pahakalle Quite a bit. I'm changing the deprecated "MAINTAINER" label to "LABEL maintainer.email..." and I indented a multi-line run command for readability.

**Comment by NonCreature0714** [comment]
@pahakalle this is far, far less sweeping than #15

**Comment by pahakalle** [comment]
Ok, let's hope this gets merged (in less than a year 😂 :)

**Comment by NonCreature0714** [comment]
Haha, yeah, I saw that... Hope so!

**Pull request merged**
